// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZdOyrNYp8BnvcD3q9b3WPilZtYbhrpk',
    appId: '1:884779701107:web:92f1b697256058c0dbab06',
    messagingSenderId: '884779701107',
    projectId: 'flutter-red-social',
    authDomain: 'flutter-red-social.firebaseapp.com',
    storageBucket: 'flutter-red-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3znGuFBklkb7N0wKNiQPG2Poxh3pqA0',
    appId: '1:884779701107:android:7af2aea15dc37bffdbab06',
    messagingSenderId: '884779701107',
    projectId: 'flutter-red-social',
    storageBucket: 'flutter-red-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkjP9NK3HbDYYeHd4oQObsickeI1ztKY',
    appId: '1:884779701107:ios:448af63abc8e24bcdbab06',
    messagingSenderId: '884779701107',
    projectId: 'flutter-red-social',
    storageBucket: 'flutter-red-social.appspot.com',
    iosBundleId: 'com.example.redSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkjP9NK3HbDYYeHd4oQObsickeI1ztKY',
    appId: '1:884779701107:ios:448af63abc8e24bcdbab06',
    messagingSenderId: '884779701107',
    projectId: 'flutter-red-social',
    storageBucket: 'flutter-red-social.appspot.com',
    iosBundleId: 'com.example.redSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ZdOyrNYp8BnvcD3q9b3WPilZtYbhrpk',
    appId: '1:884779701107:web:bc49c8f3415d9954dbab06',
    messagingSenderId: '884779701107',
    projectId: 'flutter-red-social',
    authDomain: 'flutter-red-social.firebaseapp.com',
    storageBucket: 'flutter-red-social.appspot.com',
  );
}
